language: cpp

compiler: 
    - gcc
    - clang

#before_install:
#    - echo $LANG
#    - echo $LC_ALL
#    - gem update --system
#    - getm --version

#before_script:
#   - 

script: gcc test.c

#after_success:


#branches:
#    only:
#        - master
#        - 1.8.7
#        - 2.2
#        - /^\d+\./

#notification:
#    email: flase

#env:
    - RVM=2.0.0 LANG\"en_US.UTF-8"

os:
    - linux




